### ISSUE TITLE
Brakujący plik: 09_ciagle/bus_stop.jpg

### ISSUE THREAD

**Issue by dos1** [jpotoniec/mp#2]
```
LaTeX Warning: File `09_ciagle/bus_stop.jpg' not found on input line 64.


! Package pdftex.def Error: File `09_ciagle/bus_stop.jpg' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.64 \end{frame}

? 
```

**Comment by jpotoniec** [comment]
W dniu 14.06.2015 o 09:08, Sebastian Krzyszkowiak pisze:

> |LaTeX Warning: File `09_ciagle/bus_stop.jpg' not found on input line 64.
> 
> ! Package pdftex.def Error: File `09_ciagle/bus_stop.jpg' not found.
> 
> See the pdftex.def package documentation for explanation.
> Type  H <return>  for immediate help.
>   ...
> 
> l.64 \end{frame}
> 
> ?
> |
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jpotoniec/mp/issues/2.
> 
> Dziękuję, poprawione

## 

Jędrzej Potoniec
